"""The SHA-256 digest construction behind the audit_event hash chain
(NFR-10, issue #36).

Each row's ``entry_hash`` is a digest over its own content plus its
predecessor's ``entry_hash`` (``prev_hash``), so an out-of-band ``UPDATE``,
``DELETE`` or re-order is *detectable*, even though - holding table-owner
credentials - it cannot be *prevented*. See
``docs/architecture/data-model.md`` for the full design writeup and
``docs/adr/0017-audit-hash-chain.md`` for the rejected alternatives.

**Canonical form.** A single JSON object,
``json.dumps(..., sort_keys=True, separators=(",", ":"), ensure_ascii=False)``
encoded as UTF-8 - the same idiom already used by
``transform/src/nptc_transform/report_writer.py`` for a byte-identical
canonical form, whose module docstring is the prior art for why
``sort_keys=True`` is the right tool and where it stops. A JSON object is
self-delimiting, so ``("ab", "c")`` cannot collide with ``("a", "bc")`` the
way a naively-joined string could.

**Field coverage.** The digest covers every ``audit_event`` column except
two - see ``EXCLUDED_DIGEST_COLUMNS`` below - and the exclusion set is
explicit and tested (``backend/tests/test_audit_hashing.py``), not
implied. ``prev_hash`` itself *is* covered (it is not in the exclusion
set): ``compute_entry_hash`` takes it as an explicit argument only because
the caller (``nptc.audit.writer.append_audit_event``) reads it from the
chain's tail before the rest of the row's fields are assembled, not
because it is excluded from the digest.
"""

from __future__ import annotations

import hashlib
import ipaddress
import json
import uuid
from collections.abc import Mapping
from datetime import UTC, datetime
from typing import Final

from sqlalchemy.sql.selectable import FromClause

#: The first row's `prev_hash` - there is no predecessor to point to.
GENESIS_HASH: Final[str] = "0" * 64

#: Folded into every digest's payload (see `compute_entry_hash`) so a
#: future change to the digest construction itself is distinguishable from
#: a change to the data being hashed - a verifier can tell "this row used
#: an old scheme" apart from "this row was tampered with".
HASH_SCHEME: Final[int] = 1

#: `entry_hash` is the digest itself, so it cannot be an input to its own
#: computation. `sequence` is `GENERATED ALWAYS AS IDENTITY`: its value is
#: unknowable before the `INSERT` and so cannot be folded into that row's
#: own digest - see `nptc.audit.writer`'s module docstring for why
#: `GENERATED ALWAYS` (rather than `GENERATED BY DEFAULT`, which could be
#: folded in first) was kept. Ordering is still tamper-evident without it:
#: verification walks rows in `sequence` order and each row's `prev_hash`
#: must equal its predecessor's `entry_hash`, so a deleted or reordered row
#: breaks the chain regardless of `sequence` itself never being hashed.
EXCLUDED_DIGEST_COLUMNS: Final[frozenset[str]] = frozenset({"entry_hash", "sequence"})


def digest_field_names(table: FromClause) -> frozenset[str]:
    """The set of column names the digest covers for `table` - every
    column except `EXCLUDED_DIGEST_COLUMNS`. Derived from the table's own
    columns, never hand-maintained, so a column added by a later issue is
    automatically covered unless someone deliberately adds it to
    `EXCLUDED_DIGEST_COLUMNS` - see
    `test_audit_hashing.py::test_digest_covers_every_meaningful_column`.
    """
    return frozenset(column.name for column in table.columns) - EXCLUDED_DIGEST_COLUMNS


def _normalise(value: object) -> object:
    """Per-type normalisation into something `json.dumps` can render
    deterministically. `UUID` and `ipaddress` objects become their string
    form; a `datetime` is converted to UTC first (so the same instant
    always serialises identically regardless of the timezone attached to
    it) and rendered with a fixed 6-digit microsecond field, since
    `isoformat()` alone drops trailing zero microseconds inconsistently.
    `before`/`after` (already-parsed JSON objects/arrays) recurse so their
    own nested values get the same treatment."""
    if value is None or isinstance(value, str | int | float):
        return value
    if isinstance(value, uuid.UUID):
        return str(value)
    if isinstance(
        value,
        ipaddress.IPv4Address
        | ipaddress.IPv6Address
        | ipaddress.IPv4Network
        | ipaddress.IPv6Network
        | ipaddress.IPv4Interface
        | ipaddress.IPv6Interface,
    ):
        return str(value)
    if isinstance(value, datetime):
        return value.astimezone(UTC).strftime("%Y-%m-%dT%H:%M:%S.%fZ")
    if isinstance(value, Mapping):
        return {str(key): _normalise(item) for key, item in value.items()}
    if isinstance(value, list | tuple):
        return [_normalise(item) for item in value]
    return str(value)


def canonicalise_actor_ip(value: str) -> str:
    """Renders `value` in the same textual form Postgres's `inet` type
    stores/displays it in, so the digest computed before `INSERT` and the
    value actually stored (and later re-read for the write-time
    self-check, or by `verify_chain`) are always the same string -
    independent of exactly how the caller spelled the address.

    `inet` prints a bare address (no `/`) when the mask is the full
    address width - a "host" mask, `/32` for IPv4 or `/128` for IPv6 - and
    `address/prefixlen` otherwise. Without this, an input like
    `"203.0.113.7/32"` would be hashed as submitted but stored/re-read as
    `"203.0.113.7"`, so the write-time self-check in
    `nptc.audit.writer.append_audit_event` would raise
    `AuditChainWriteError` on every such input."""
    interface = ipaddress.ip_interface(value)
    host_mask = 32 if isinstance(interface, ipaddress.IPv4Interface) else 128
    if interface.network.prefixlen == host_mask:
        return str(interface.ip)
    return f"{interface.ip}/{interface.network.prefixlen}"


def canonical_payload(fields: Mapping[str, object]) -> bytes:
    """The exact bytes that get hashed: `fields`, normalised field-by-field
    and rendered as one canonical, self-delimiting JSON object."""
    normalised = {str(key): _normalise(value) for key, value in fields.items()}
    return json.dumps(normalised, sort_keys=True, separators=(",", ":"), ensure_ascii=False).encode(
        "utf-8"
    )


def compute_entry_hash(fields: Mapping[str, object], prev_hash: str) -> str:
    """The SHA-256 digest, as a lowercase hex string, over `fields` plus
    `prev_hash` and `HASH_SCHEME`. `fields` must already exclude
    `prev_hash` itself (it is folded in here) and every name in
    `EXCLUDED_DIGEST_COLUMNS`.

    `fields` is nested under its own `"fields"` key rather than flattened
    alongside `prev_hash`/`hash_scheme` in the payload: a flat namespace
    would let a future `audit_event` column literally named `prev_hash` or
    `hash_scheme` silently collide with this function's own bookkeeping
    keys. `canonical_payload` already recurses into nested `Mapping`s via
    `_normalise`, so nesting here needs no change there."""
    payload: dict[str, object] = {
        "fields": dict(fields),
        "prev_hash": prev_hash,
        "hash_scheme": HASH_SCHEME,
    }
    return hashlib.sha256(canonical_payload(payload)).hexdigest()
