"""The append-only write path for audit_event (NFR-08, NFR-10, issue #36).

`append_audit_event` is the only sanctioned way to insert a row: every
step below exists to keep the hash chain from forking, and skipping any of
them (whether by writing raw SQL or constructing an `AuditEvent` directly)
reopens exactly the gap this issue exists to close. See
`nptc.audit.hashing` for the digest itself and `nptc.audit.verification`
for how a chain built by this writer is checked.

Sequence of operations, all inside the caller's own transaction (there is
no commit here - the caller decides when the audit event and whatever
state change it records commit together, atomically):

1. `pg_advisory_xact_lock` serialises appends across concurrent
   transactions - two concurrent appenders would otherwise both read the
   same tail and fork the chain, the principal failure mode this issue
   guards against. Needs no grant (advisory locks are role-agnostic) and
   is transaction-scoped, so it releases automatically on commit or
   rollback - not a trigger or stored function, so PRD Section 14.1 is
   untouched.
2. `session.flush()`, then read the tail (`ORDER BY sequence DESC LIMIT
   1`). The flush matters: without it, an earlier append in the same
   transaction would be invisible to this `SELECT` and the chain would
   fork within a single request.
3. `occurred_at` comes from `SELECT clock_timestamp()` - the *database*
   clock, never the client (NFR-08) - and specifically `clock_timestamp()`
   rather than `now()`, since `now()` is fixed at transaction start and
   two events appended in the same transaction would otherwise share a
   timestamp. `id` is a Python `uuid4()`. Both must be known before the
   digest is computed, since both are digest fields.
4. The digest is computed and the row inserted.
5. **Write-time self-check**: the row is re-read from the database and its
   digest recomputed from what Postgres actually stored. A JSONB
   round-trip divergence (a number literal Postgres normalises, e.g.
   `1e2` -> `100.0`) would otherwise surface as an unexplained chain break
   months later instead of a loud failure at the point of the write.

`sequence` is `GENERATED ALWAYS AS IDENTITY`, not `GENERATED BY DEFAULT`:
the latter would reintroduce the separate `GRANT USAGE ON SEQUENCE` issue
#33 deliberately designed away (see `nptc.db.models.audit`) and would let
a caller override the value - see `nptc.audit.hashing` for why `sequence`
is excluded from the digest as a consequence.
"""

from __future__ import annotations

import uuid
from typing import Any, Final

from pydantic import BaseModel, ConfigDict
from sqlalchemy import select, text
from sqlalchemy.orm import Session

from nptc.audit.hashing import GENESIS_HASH, compute_entry_hash, digest_field_names
from nptc.db.models.audit import AuditEvent


class AuditChainWriteError(RuntimeError):
    """Raised when the write-time self-check (step 5 above) finds the
    digest recomputed from what Postgres actually stored does not match
    what was written - e.g. a JSONB round-trip normalisation the digest
    construction didn't account for. A loud failure at the point of the
    write, not a silent chain break discovered later."""


#: Fixed, arbitrary key for `pg_advisory_xact_lock` (step 1 above) - any
#: fixed integer works, since advisory locks are an application-chosen
#: namespace, not tied to any table or row. Kept as a bare literal in the
#: SQL text below (not interpolated), so
#: `backend/tests/test_sql_parameterisation.py`'s AST guard - which
#: forbids building SQL from runtime data - has nothing to flag; there is
#: no runtime data here in the first place. Exported as a constant purely
#: for tests that want to name it; keep the two literals in sync if this
#: is ever changed.
AUDIT_APPEND_LOCK_KEY: Final[int] = 64602913

_ACQUIRE_APPEND_LOCK_SQL = text("SELECT pg_advisory_xact_lock(64602913)")
_CLOCK_TIMESTAMP_SQL = text("SELECT clock_timestamp()")


class AuditContext(BaseModel):
    """Who/what is making the write that `append_audit_event` records -
    always supplied, never optional with a default. An optional audit
    context is exactly how an NFR-08 gap gets introduced: a call site that
    forgets to pass one would otherwise silently emit an unattributed
    event instead of failing to type-check."""

    model_config = ConfigDict(frozen=True)

    #: None for a system-initiated event with no human actor.
    actor_user_id: uuid.UUID | None
    actor_ip: str | None
    user_agent: str | None
    correlation_id: uuid.UUID

    @classmethod
    def system(cls) -> AuditContext:
        """A system-initiated event: no human actor, no IP, no user
        agent, and a fresh `correlation_id` since there is no inbound
        request to inherit one from."""
        return cls(
            actor_user_id=None,
            actor_ip=None,
            user_agent=None,
            correlation_id=uuid.uuid4(),
        )


def _read_prev_hash(session: Session) -> str:
    tail = session.execute(
        select(AuditEvent.entry_hash).order_by(AuditEvent.sequence.desc()).limit(1)
    ).scalar_one_or_none()
    return tail if tail is not None else GENESIS_HASH


def _row_digest_fields(row: AuditEvent) -> dict[str, Any]:
    names = digest_field_names(AuditEvent.__table__) - {"prev_hash"}
    return {name: getattr(row, name) for name in names}


def append_audit_event(
    session: Session,
    ctx: AuditContext,
    *,
    action: str,
    entity_type: str,
    entity_id: str,
    before: dict[str, object] | None = None,
    after: dict[str, object] | None = None,
    reason: str | None = None,
) -> AuditEvent:
    """Appends one row to `audit_event`, computing and linking its hash
    chain fields. See the module docstring for the exact sequence and why
    each step exists."""
    session.execute(_ACQUIRE_APPEND_LOCK_SQL)

    session.flush()
    prev_hash = _read_prev_hash(session)

    occurred_at = session.execute(_CLOCK_TIMESTAMP_SQL).scalar_one()
    event_id = uuid.uuid4()

    fields: dict[str, Any] = {
        "id": event_id,
        "occurred_at": occurred_at,
        "actor_user_id": ctx.actor_user_id,
        "actor_ip": ctx.actor_ip,
        "user_agent": ctx.user_agent,
        "correlation_id": ctx.correlation_id,
        "action": action,
        "entity_type": entity_type,
        "entity_id": entity_id,
        "before": before,
        "after": after,
        "reason": reason,
    }
    entry_hash = compute_entry_hash(fields, prev_hash)

    event = AuditEvent(prev_hash=prev_hash, entry_hash=entry_hash, **fields)
    session.add(event)
    session.flush()

    session.refresh(event)
    recomputed = compute_entry_hash(_row_digest_fields(event), event.prev_hash)
    if recomputed != event.entry_hash:
        raise AuditChainWriteError(
            "entry_hash mismatch immediately after write for audit_event "
            f"id={event.id}: computed {recomputed}, stored {event.entry_hash}"
        )

    return event
