"""The append-only write path for `audit_event` (NFR-08, NFR-10).

Domain code wanting a field-level diff calls `nptc.audit.recording.record_change` or
`record_snapshot_change`, not this module with a hand-built `before`/`after`.

`append_audit_event` is the only sanctioned way to insert a row. Every step below keeps the
hash chain from forking, and skipping one (raw SQL, or constructing an `AuditEvent` directly)
reopens that gap. `nptc.audit.hashing` builds the digest and `nptc.audit.verification` checks
a chain this writer built. Design and rejected alternatives: ADR-0017.

Everything runs in the caller's transaction. There is no commit here, so the audit event and
the state change it records commit together.

1. `pg_advisory_xact_lock` serialises appends. Two concurrent appenders would otherwise read
   the same tail and fork the chain. It needs no grant, it is transaction-scoped so it
   releases on commit or rollback, and it is not a trigger or stored function (PRD Section
   14.1).
1a. Straight after the lock, `SELECT current_setting('transaction_isolation')` must return
    `'read committed'`, or `AuditIsolationLevelError` is raised. Under `REPEATABLE READ` or
    `SERIALIZABLE` the snapshot is fixed at or before the first statement, so an appender that
    wins the lock after the previous holder commits can still read a tail that predates that
    commit. The lock stops the appends running concurrently, not forking.
2. `session.flush()`, then read the tail (`ORDER BY sequence DESC LIMIT 1`). Without the
   flush, an earlier append in the same transaction is invisible to the `SELECT` and the chain
   forks within one request.
3. `occurred_at` is `SELECT clock_timestamp()`: the database clock, never the client (NFR-08),
   and not `now()`, which is fixed at transaction start and would give two events in one
   transaction the same timestamp. `id` is a Python `uuid4()`. Both are digest fields, so both
   must be known before the digest is computed.
4. `ctx.actor_ip`, if set, goes through `nptc.audit.hashing.canonicalise_actor_ip` before the
   digest, into the form Postgres's `inet` stores. Otherwise `"203.0.113.7/32"` would hash as
   submitted but be re-read as `"203.0.113.7"`, and step 6 would raise `AuditChainWriteError`.
   The canonical string is used for both the digest and the stored value.
5. The digest is computed and the row inserted.
6. **Write-time self-check**: the row is re-read and its digest recomputed from what Postgres
   stored. A JSONB round-trip divergence (Postgres normalises `1e2` to `100.0`) would
   otherwise surface as an unexplained chain break months later.

`sequence` is `GENERATED ALWAYS AS IDENTITY`. `GENERATED BY DEFAULT` would reintroduce a
separate `GRANT USAGE ON SEQUENCE` and let a caller override the value (ADR-0017;
`nptc.audit.hashing` explains why `sequence` is outside the digest).
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Any, Final

from pydantic import BaseModel, ConfigDict
from sqlalchemy import select, text
from sqlalchemy.orm import Session

from nptc.audit.hashing import (
    GENESIS_HASH,
    canonicalise_actor_ip,
    compute_entry_hash,
    digest_field_names,
)
from nptc.db.models.audit import AuditEvent


class AuditChainWriteError(RuntimeError):
    """Raised when the write-time self-check (step 6 above) finds that the digest recomputed
    from what Postgres stored differs from what was written, for example a JSONB round-trip
    normalisation the digest construction did not account for. A loud failure at the write, not
    a chain break found later."""


class AuditIsolationLevelError(RuntimeError):
    """Raised when the caller's transaction is not `READ COMMITTED` (step 1a above). Above that
    level the advisory lock serialises execution, but a snapshot fixed before the previous
    holder's commit can still read a stale tail, so this fails loudly rather than risk a silent
    fork."""


#: Fixed, arbitrary key for `pg_advisory_xact_lock` (step 1): advisory locks use an
#: application-chosen namespace, tied to no table or row. It is bound as `:key`, not
#: interpolated, so there is one literal to keep in sync, and
#: `test_sql_parameterisation.py`'s AST guard, which forbids building the SQL *string* from
#: runtime data, allows it.
AUDIT_APPEND_LOCK_KEY: Final[int] = 64602913

_ACQUIRE_APPEND_LOCK_SQL = text("SELECT pg_advisory_xact_lock(:key)")
_CHECK_ISOLATION_LEVEL_SQL = text("SELECT current_setting('transaction_isolation')")
_CLOCK_TIMESTAMP_SQL = text("SELECT clock_timestamp()")
_REQUIRED_ISOLATION_LEVEL: Final[str] = "read committed"


class AuditContext(BaseModel):
    """Who is making the write that `append_audit_event` records. Always supplied, never
    optional: an optional context is how an NFR-08 gap gets in, because a call site that
    forgets it would emit an unattributed event instead of failing to type-check."""

    model_config = ConfigDict(frozen=True)

    #: None for a system-initiated event with no human actor.
    actor_user_id: uuid.UUID | None
    actor_ip: str | None
    user_agent: str | None
    correlation_id: uuid.UUID

    @classmethod
    def system(cls) -> AuditContext:
        """A system-initiated event: no human actor, no IP, no user
        agent, and a fresh `correlation_id` since there is no inbound
        request to inherit one from."""
        return cls(
            actor_user_id=None,
            actor_ip=None,
            user_agent=None,
            correlation_id=uuid.uuid4(),
        )


def _read_prev_hash(session: Session) -> str:
    tail = session.execute(
        select(AuditEvent.entry_hash).order_by(AuditEvent.sequence.desc()).limit(1)
    ).scalar_one_or_none()
    return tail if tail is not None else GENESIS_HASH


def _row_digest_fields(row: AuditEvent) -> dict[str, Any]:
    names = digest_field_names(AuditEvent.__table__) - {"prev_hash"}
    return {name: getattr(row, name) for name in names}


def acquire_append_lock(session: Session) -> None:
    """Acquires the audit append lock (steps 1 and 1a above) without writing a row.

    The catalogue-entry writers call this before their first session-touching statement, so the
    append lock is always taken before any row or collision lock and the lock-ordering cycles
    cannot form (ADR-0035). A later `append_audit_event` in the same transaction re-asserts the
    lock, which is cheap and safe because `pg_advisory_xact_lock` nests within a transaction.
    """
    session.execute(_ACQUIRE_APPEND_LOCK_SQL, {"key": AUDIT_APPEND_LOCK_KEY})

    isolation_level: str = session.execute(_CHECK_ISOLATION_LEVEL_SQL).scalar_one()
    if isolation_level != _REQUIRED_ISOLATION_LEVEL:
        raise AuditIsolationLevelError(
            "append_audit_event requires READ COMMITTED isolation to keep the "
            f"chain from forking, got {isolation_level!r}"
        )


def append_audit_event(
    session: Session,
    ctx: AuditContext,
    *,
    action: str,
    entity_type: str,
    entity_id: str,
    before: dict[str, object] | None = None,
    after: dict[str, object] | None = None,
    reason: str | None = None,
) -> AuditEvent:
    """Appends one row to `audit_event`, computing and linking its hash
    chain fields. See the module docstring for the exact sequence and why
    each step exists."""
    acquire_append_lock(session)

    session.flush()
    prev_hash = _read_prev_hash(session)

    occurred_at: datetime = session.execute(_CLOCK_TIMESTAMP_SQL).scalar_one()
    event_id = uuid.uuid4()
    actor_ip = canonicalise_actor_ip(ctx.actor_ip) if ctx.actor_ip is not None else None

    fields: dict[str, Any] = {
        "id": event_id,
        "occurred_at": occurred_at,
        "actor_user_id": ctx.actor_user_id,
        "actor_ip": actor_ip,
        "user_agent": ctx.user_agent,
        "correlation_id": ctx.correlation_id,
        "action": action,
        "entity_type": entity_type,
        "entity_id": entity_id,
        "before": before,
        "after": after,
        "reason": reason,
    }
    entry_hash = compute_entry_hash(fields, prev_hash)

    event = AuditEvent(prev_hash=prev_hash, entry_hash=entry_hash, **fields)
    session.add(event)
    session.flush()

    session.refresh(event)
    recomputed = compute_entry_hash(_row_digest_fields(event), event.prev_hash)
    if recomputed != event.entry_hash:
        raise AuditChainWriteError(
            "entry_hash mismatch immediately after write for audit_event "
            f"id={event.id}: computed {recomputed}, stored {event.entry_hash}"
        )

    return event
