/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The current session's user, roles and permissions
         * @description Never 401s for an anonymous caller.
         *
         *     "Who am I?" is a legitimate question with a legitimate answer for a
         *     signed-out visitor - `authenticated: false` - and the SPA asks it on
         *     every cold load, before it knows whether it has a session. Answering
         *     401 would make an ordinary first page load indistinguishable from a
         *     genuine credential failure. A *bad* token still 401s, because
         *     `current_principal` raises rather than degrading to anonymous.
         */
        get: operations["read_current_session_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalogue/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One page of published catalogue entries
         * @description Keyset paging on `business_key`, ascending. Pass the response's
         *     `next_cursor` back as `after` for the following page; a `null`
         *     `next_cursor` means there is no following page.
         *
         *     There is no `offset` and no total count, on purpose (ADR-0024): an
         *     offset re-reads and re-skips every earlier row on every page, and drops
         *     or repeats rows outright when a concurrent insert shifts the window
         *     mid-scan.
         */
        get: operations["list_entries_api_v1_catalogue_entries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalogue/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search the published catalogue by term
         * @description Best match first, ties broken by `business_key` so the order is
         *     total and paging cannot drop or repeat a row inside a tie.
         *
         *     A query below the similarity threshold returns an empty page rather
         *     than a broadened match. That is the intended behaviour: a search that
         *     quietly matches everything is worse than one that matches nothing,
         *     because the caller cannot tell it from a working search over a catalogue
         *     that genuinely has nothing to offer.
         */
        get: operations["search_api_v1_catalogue_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalogue/entries/{business_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One published catalogue entry, with everything attached to it */
        get: operations["read_entry_api_v1_catalogue_entries__business_key__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalogue/entries/{business_key}/designations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** An entry's active synonyms and non-en-AU preferred variants */
        get: operations["read_designations_api_v1_catalogue_entries__business_key__designations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalogue/entries/{business_key}/bindings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * An entry's SNOMED CT code bindings, including retired ones
         * @description Retired bindings are included (FR-08): a client holding a code that
         *     has been inactivated learns so here, together with the reason and any
         *     successor code.
         */
        get: operations["read_bindings_api_v1_catalogue_entries__business_key__bindings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalogue/entries/{business_key}/properties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** An entry's recorded property values */
        get: operations["read_properties_api_v1_catalogue_entries__business_key__properties_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Binding
         * @description A SNOMED CT code binding, active or retired.
         *
         *     `code` is a string, always (FR-06). `display_term` is `fsn` with its
         *     semantic tag removed exactly once, by FR-83's single sanctioned
         *     renderer - it is derived here rather than stored, because a stored
         *     stripped value is indistinguishable from an unstripped one and that
         *     ambiguity is what makes double-stripping possible.
         *
         *     A retired binding carries `retirement_reason` and, where PRD FR-08's
         *     replacement case applies, `replaced_by_code` - the successor's *code*,
         *     which is what a client holding the retired one needs in order to move.
         */
        Binding: {
            /** System */
            system: string;
            /** Code */
            code: string; // deliberately stale for issue #147 CI verification
            /** Fsn */
            fsn: string;
            /** Display Term */
            display_term: string;
            /** Au Preferred Term */
            au_preferred_term: string | null;
            /** Edition Hint */
            edition_hint: string;
            /** Status */
            status: string;
            /** Retirement Reason */
            retirement_reason: string | null;
            /** Replaced By Code */
            replaced_by_code: string | null;
        };
        /** BindingList */
        BindingList: {
            /** Items */
            items: components["schemas"]["Binding"][];
        };
        /**
         * Designation
         * @description A catalogue-authored synonym, or a preferred variant in a language
         *     other than en-AU.
         *
         *     The catalogue's own en-AU preferred term is **not** here - it is
         *     `EntrySummary.preferred_term`, and ADR-0022 makes its absence from
         *     `designation` a database invariant rather than a convention. A client
         *     building a term list needs both: `preferred_term`, plus these.
         */
        Designation: {
            /** Term */
            term: string;
            /** Use */
            use: string;
            /** Language */
            language: string;
            /** Status */
            status: string;
            /** Length */
            length: number;
        };
        /** DesignationList */
        DesignationList: {
            /** Items */
            items: components["schemas"]["Designation"][];
        };
        /**
         * EntryDetail
         * @description A summary plus everything attached to the entry.
         *
         *     One response rather than making a client fetch four: the sub-resources
         *     are also served individually (a client refreshing one panel should not
         *     re-fetch the lot), but the common case is "show me this entry", and
         *     four round trips for one screen is a contract that pushes latency onto
         *     every consumer.
         */
        EntryDetail: {
            /** Business Key */
            business_key: string;
            /** Preferred Term */
            preferred_term: string;
            /** Length */
            length: number;
            /** Status */
            status: string;
            /** Specimen Unconstrained */
            specimen_unconstrained: boolean;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Designations */
            designations: components["schemas"]["Designation"][];
            /** Bindings */
            bindings: components["schemas"]["Binding"][];
            /** Properties */
            properties: components["schemas"]["PropertyValue"][];
        };
        /**
         * EntryPage
         * @description `next_cursor` is `null` on the last page - which is the *only*
         *     reliable signal that paging is finished. A client must not infer the end
         *     from a short page: a page can be short and still have a successor.
         */
        EntryPage: {
            /** Items */
            items: components["schemas"]["EntrySummary"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /**
         * EntrySummary
         * @description An entry as it appears in a list or a search result.
         *
         *     `length` is FR-85's published figure - the character count of the
         *     catalogue's own preferred term, computed by `CatalogueEntry.length` and
         *     never stored, so it cannot drift from the term it describes.
         */
        EntrySummary: {
            /** Business Key */
            business_key: string;
            /** Preferred Term */
            preferred_term: string;
            /** Length */
            length: number;
            /** Status */
            status: string;
            /** Specimen Unconstrained */
            specimen_unconstrained: boolean;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ErrorResponse
         * @description Every refusal this API makes has this shape - one sentence saying
         *     what to do next, and deliberately nothing else. It never names a role,
         *     a permission or an internal identifier (FR-44, NFR-04).
         */
        ErrorResponse: {
            /** Detail */
            detail: string;
        };
        /** PropertyList */
        PropertyList: {
            /** Items */
            items: components["schemas"]["PropertyValue"][];
        };
        /**
         * PropertyValue
         * @description One property value, rendered by its datatype's own handler.
         *
         *     `value` is whatever that handler's `serialise(..., JSON)` returns, so a
         *     new datatype (FR-77) appears here correctly without this module
         *     changing. `ordinal` is meaningful for a multi-valued property: it is the
         *     position of this value among that property's values, zero-based.
         */
        PropertyValue: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Datatype */
            datatype: string;
            /** Cardinality */
            cardinality: string;
            /** Ordinal */
            ordinal: number;
            /** Value */
            value: unknown;
            /** Justification */
            justification: string | null;
        };
        /**
         * SearchHit
         * @description A summary plus its relevance score.
         *
         *     The score is exposed because it is what the ordering is, and a client
         *     that cannot see it cannot tell a confident single match from a page of
         *     weak ones. It is comparable *within* one response only - it is a
         *     trigram similarity against this particular query, not a quality rating
         *     of the entry.
         */
        SearchHit: {
            /** Business Key */
            business_key: string;
            /** Preferred Term */
            preferred_term: string;
            /** Length */
            length: number;
            /** Status */
            status: string;
            /** Specimen Unconstrained */
            specimen_unconstrained: boolean;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Score
             * @description Trigram similarity against `q`, between 0 and 1.
             */
            score: number;
        };
        /** SearchPage */
        SearchPage: {
            /** Items */
            items: components["schemas"]["SearchHit"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /**
         * SessionResponse
         * @description What the browser is allowed to know about its own session.
         *
         *     `user` is `nptc.auth.identity.UserRef`, reused rather than redefined:
         *     it is this codebase's existing NFR-04 serialisation boundary and
         *     structurally excludes `app_user.id`. Defining a second response model
         *     with the same fields is exactly how that internal id eventually leaks.
         *
         *     `permissions` is present because the shell needs to decide what to
         *     *render*, and rendering is presentation, not access control (NFR-20) -
         *     every one of these permissions is re-checked server-side at the
         *     endpoint that uses it. `roles` is included for the account screen
         *     (FR-40), which shows a user their own roles.
         */
        SessionResponse: {
            /** Authenticated */
            authenticated: boolean;
            user: components["schemas"]["UserRef"] | null;
            /** Roles */
            roles: string[];
            /** Permissions */
            permissions: string[];
            /** Mfa Satisfied */
            mfa_satisfied: boolean;
        };
        /**
         * UserRef
         * @description The NFR-04 serialisation boundary: what any API response or export
         *     is allowed to say about a user. No ``id`` field, ever - the internal
         *     UUID must never escape past this type. #43/#142/#143 route through
         *     this structurally instead of relying on reviewer memory that the UUID
         *     must not leak.
         */
        UserRef: {
            /** Username */
            username: string | null;
            /** Display Name */
            display_name: string | null;
            /** Organisation */
            organisation: string | null;
            /** Status */
            status: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    read_current_session_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description No credential was presented where one is required, or the token could not be verified. Carries `WWW-Authenticate: Bearer`. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authenticated, but not permitted. When the permission would have been granted by a role suppressed for want of MFA, this carries an RFC 9470 `WWW-Authenticate: Bearer error="insufficient_user_authentication"` challenge instead of a bare denial (NFR-06). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The token resolved to more than one candidate account, or to an untrusted auto-link candidate. A human must resolve it (NFR-05). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_entries_api_v1_catalogue_entries_get: {
        parameters: {
            query?: {
                /** @description Maximum entries in this page. */
                limit?: number;
                /** @description The `next_cursor` from the previous page. Pass it back unmodified, and do not construct one. */
                after?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntryPage"];
                };
            };
            /** @description A credential was presented and could not be verified. Sending no credential at all is not an error on these endpoints. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A query or path parameter was unprocessable - a business key that is not `NPTC-nnnnnn`, a blank search query, a cursor this API did not issue (including one issued for a different `q`), or a `limit` outside its range. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    search_api_v1_catalogue_search_get: {
        parameters: {
            query: {
                /** @description Free text. Matched against each entry's preferred term and its active synonyms, insensitive to case and to diacritics, and tolerant of typographical error (FR-15). */
                q: string;
                /** @description Maximum entries in this page. */
                limit?: number;
                /** @description The `next_cursor` from the previous page. Opaque: pass it back unmodified, and do not construct one. It is bound to the `q` it was issued for - sending it with a different `q` is a 422, not a meaningless page. */
                after?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchPage"];
                };
            };
            /** @description A credential was presented and could not be verified. Sending no credential at all is not an error on these endpoints. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A query or path parameter was unprocessable - a business key that is not `NPTC-nnnnnn`, a blank search query, a cursor this API did not issue (including one issued for a different `q`), or a `limit` outside its range. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    read_entry_api_v1_catalogue_entries__business_key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The entry's public identifier, e.g. `NPTC-000247` (FR-03). */
                business_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntryDetail"];
                };
            };
            /** @description A credential was presented and could not be verified. Sending no credential at all is not an error on these endpoints. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No entry in the published catalogue has this business key. An entry that exists but is not published (draft, deprecated or withdrawn) is reported identically, on purpose - a distinguishable response would confirm the key exists. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A query or path parameter was unprocessable - a business key that is not `NPTC-nnnnnn`, a blank search query, a cursor this API did not issue (including one issued for a different `q`), or a `limit` outside its range. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A published code binding's stored Fully Specified Name is not in the form the terminology server serves, so its display term cannot be rendered. This is a data fault in the catalogue, not a fault in the request; it needs an administrator, and retrying will not clear it. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    read_designations_api_v1_catalogue_entries__business_key__designations_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The entry's public identifier, e.g. `NPTC-000247` (FR-03). */
                business_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DesignationList"];
                };
            };
            /** @description A credential was presented and could not be verified. Sending no credential at all is not an error on these endpoints. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No entry in the published catalogue has this business key. An entry that exists but is not published (draft, deprecated or withdrawn) is reported identically, on purpose - a distinguishable response would confirm the key exists. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A query or path parameter was unprocessable - a business key that is not `NPTC-nnnnnn`, a blank search query, a cursor this API did not issue (including one issued for a different `q`), or a `limit` outside its range. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    read_bindings_api_v1_catalogue_entries__business_key__bindings_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The entry's public identifier, e.g. `NPTC-000247` (FR-03). */
                business_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BindingList"];
                };
            };
            /** @description A credential was presented and could not be verified. Sending no credential at all is not an error on these endpoints. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No entry in the published catalogue has this business key. An entry that exists but is not published (draft, deprecated or withdrawn) is reported identically, on purpose - a distinguishable response would confirm the key exists. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A query or path parameter was unprocessable - a business key that is not `NPTC-nnnnnn`, a blank search query, a cursor this API did not issue (including one issued for a different `q`), or a `limit` outside its range. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A published code binding's stored Fully Specified Name is not in the form the terminology server serves, so its display term cannot be rendered. This is a data fault in the catalogue, not a fault in the request; it needs an administrator, and retrying will not clear it. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    read_properties_api_v1_catalogue_entries__business_key__properties_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The entry's public identifier, e.g. `NPTC-000247` (FR-03). */
                business_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyList"];
                };
            };
            /** @description A credential was presented and could not be verified. Sending no credential at all is not an error on these endpoints. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No entry in the published catalogue has this business key. An entry that exists but is not published (draft, deprecated or withdrawn) is reported identically, on purpose - a distinguishable response would confirm the key exists. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A query or path parameter was unprocessable - a business key that is not `NPTC-nnnnnn`, a blank search query, a cursor this API did not issue (including one issued for a different `q`), or a `limit` outside its range. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
