/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The current session's user, roles and permissions
         * @description Never 401s for an anonymous caller.
         *
         *     "Who am I?" is a legitimate question with a legitimate answer for a
         *     signed-out visitor - `authenticated: false` - and the SPA asks it on
         *     every cold load, before it knows whether it has a session. Answering
         *     401 would make an ordinary first page load indistinguishable from a
         *     genuine credential failure. A *bad* token still 401s, because
         *     `current_principal` raises rather than degrading to anonymous.
         */
        get: operations["read_current_session_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalogue/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One page of published catalogue entries
         * @description Keyset paging on `business_key`, ascending. Pass the response's
         *     `next_cursor` back as `after` for the following page; a `null`
         *     `next_cursor` means there is no following page.
         *
         *     There is no `offset` and no total count, on purpose (ADR-0024): an
         *     offset re-reads and re-skips every earlier row on every page, and drops
         *     or repeats rows outright when a concurrent insert shifts the window
         *     mid-scan.
         */
        get: operations["list_entries_api_v1_catalogue_entries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalogue/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search the published catalogue by term
         * @description Best match first, ties broken by `business_key` so the order is
         *     total and paging cannot drop or repeat a row inside a tie.
         *
         *     A query below the similarity threshold returns an empty page rather
         *     than a broadened match. That is the intended behaviour: a search that
         *     quietly matches everything is worse than one that matches nothing,
         *     because the caller cannot tell it from a working search over a catalogue
         *     that genuinely has nothing to offer.
         */
        get: operations["search_api_v1_catalogue_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalogue/entries/{business_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One published catalogue entry, with everything attached to it */
        get: operations["read_entry_api_v1_catalogue_entries__business_key__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalogue/entries/{business_key}/designations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** An entry's active synonyms and non-en-AU preferred variants */
        get: operations["read_designations_api_v1_catalogue_entries__business_key__designations_get"];
        put?: never;
        /** Add one or more synonyms, or a non-en-AU preferred term, to a catalogue entry */
        post: operations["add_designations_api_v1_catalogue_entries__business_key__designations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalogue/entries/{business_key}/bindings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * An entry's SNOMED CT code bindings, including retired ones
         * @description Retired bindings are included (FR-08): a client holding a code that
         *     has been inactivated learns so here, together with the reason and any
         *     successor code.
         */
        get: operations["read_bindings_api_v1_catalogue_entries__business_key__bindings_get"];
        put?: never;
        /** Bind a SNOMED CT code to a catalogue entry */
        post: operations["bind_code_api_v1_catalogue_entries__business_key__bindings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalogue/entries/{business_key}/properties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** An entry's recorded property values */
        get: operations["read_properties_api_v1_catalogue_entries__business_key__properties_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalogue/entries/{business_key}/bindings/{code}/retirement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retire an entry's active code binding */
        post: operations["retire_binding_api_v1_catalogue_entries__business_key__bindings__code__retirement_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalogue/entries/{business_key}/bindings/{code}/replacement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retire an entry's active code binding and bind its successor
         * @description Runs `retire_binding` -> `create_binding` -> `link_replacement` in
         *     that order, inside this request's one transaction (see the module
         *     docstring) - `code`/`fsn`/etc. of the successor are the caller's own,
         *     exactly like `bind_code` above.
         */
        post: operations["replace_binding_api_v1_catalogue_entries__business_key__bindings__code__replacement_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalogue/entries/{business_key}/designations/amendment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Edit an entry's active designation in place */
        post: operations["amend_designation_route_api_v1_catalogue_entries__business_key__designations_amendment_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalogue/entries/{business_key}/designations/retirement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retire an entry's active designation */
        post: operations["retire_designation_route_api_v1_catalogue_entries__business_key__designations_retirement_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalogue/entries/{business_key}/designations/acknowledgement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Acknowledge a warning-severity collision on this entry */
        post: operations["acknowledge_designation_collision_api_v1_catalogue_entries__business_key__designations_acknowledgement_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/registry/properties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List property definitions */
        get: operations["list_properties_api_v1_registry_properties_get"];
        put?: never;
        /** Create a property definition */
        post: operations["create_property_api_v1_registry_properties_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/registry/properties/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one property definition */
        get: operations["get_property_api_v1_registry_properties__key__get"];
        put?: never;
        post?: never;
        /**
         * Delete a property definition (always refused)
         * @description Always refuses (FR-11) - `property_definition` has no `DELETE` grant
         *     at the database layer at all (issue #51). `key` is accepted (and, for a
         *     genuinely unknown key, still refused the same way, not 404'd) so the
         *     response is uniform regardless of whether the key exists - the caller's
         *     mistake either way is asking to delete at all, not naming the wrong
         *     key.
         */
        delete: operations["delete_property_api_v1_registry_properties__key__delete"];
        options?: never;
        head?: never;
        /** Amend a property definition */
        patch: operations["amend_property_api_v1_registry_properties__key__patch"];
        trace?: never;
    };
    "/api/v1/registry/properties/{key}/deprecation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deprecate a property definition */
        post: operations["deprecate_property_api_v1_registry_properties__key__deprecation_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AcknowledgeCollisionRequest
         * @description The body of `POST .../designations/acknowledgement`. `term` is the
         *     surface form the caller is acknowledging a warning for - resolved to a
         *     comparison key here (`nptc.catalogue.designations.clean_term` then
         *     `nptc_shared.similarity.collision_key`), matching what
         *     `warning_collisions` itself keys on, so acknowledging any surface form
         *     that folds to the same key silences the same warning.
         */
        AcknowledgeCollisionRequest: {
            /**
             * Language
             * @default en-AU
             */
            language: string;
            /** Term */
            term: string;
            /** Reason */
            reason: string;
        };
        /**
         * AddDesignationsRequest
         * @description The body of `POST /catalogue/entries/{business_key}/designations`.
         *
         *     `use` is typed against `DesignationUse` (matching `CodeBindingEditionHint`'s
         *     own precedent in `catalogue_bindings.py`), so an unrecognised value is a
         *     pydantic 422 before any row is touched, rather than an unmapped
         *     `ck_designation_use` `IntegrityError`. `terms` is a batch - the common
         *     case is pasting a delimiter-corrupted synonym cell (FR-04) - but a
         *     preferred variant permits at most one, since at most one can ever be
         *     active per `(entry, language)`. Capped at `_MAX_TERMS_PER_BATCH`: each
         *     term holds a `pg_advisory_xact_lock` until commit and costs its own
         *     collision-check flush (`add_synonyms`'s own docstring), so an unbounded
         *     batch is an unbounded amount of lock contention for one request (issue
         *     #224 review finding 4).
         */
        AddDesignationsRequest: {
            /**
             * Language
             * @default en-AU
             */
            language: string;
            /** Terms */
            terms: string[];
            /** @default synonym */
            use: components["schemas"]["DesignationUse"];
            /** Reason */
            reason: string;
        };
        /**
         * AmendDesignationRequest
         * @description The body of `POST .../designations/amendment`. `term` addresses the
         *     designation to edit; `new_term` is what it becomes. Editing in place
         *     (rather than retire-and-re-add) is `nptc.catalogue.designations.
         *     amend_designation`'s own choice - see that function's docstring.
         */
        AmendDesignationRequest: {
            /**
             * Language
             * @default en-AU
             */
            language: string;
            /** Term */
            term: string;
            /** New Term */
            new_term: string;
            /** Reason */
            reason: string;
        };
        /** AmendDesignationResult */
        AmendDesignationResult: {
            designation: components["schemas"]["Designation"];
            /** Warnings */
            warnings: components["schemas"]["CollisionWarning"][];
        };
        /**
         * AmendPropertyDefinitionRequest
         * @description The body of `PATCH /registry/properties/{key}`. Deliberately carries
         *     no `key` field (FR-12) and forbids any extra field a client might try to
         *     smuggle one in as - `extra="forbid"` turns a `key` in the body into a
         *     pydantic 422 before this ever reaches `nptc.db.definitions.
         *     amend_definition`.
         *
         *     **An explicit `null` on a known field is refused, not a silent no-op**
         *     (issue #223 review finding 9). None of these fields is a nullable
         *     domain value, so a client sending `{"label": null, ...}` almost
         *     certainly meant to omit the field, not clear it - `_reject_explicit_null`
         *     below distinguishes "omitted" from "provided as null" via
         *     `model_fields_set`, which `changes()` cannot do once every field has
         *     collapsed to `None`.
         */
        AmendPropertyDefinitionRequest: {
            /** Label */
            label?: string | null;
            /** Required For Submission */
            required_for_submission?: boolean | null;
            /** Required For Publication */
            required_for_publication?: boolean | null;
            /** Filterable */
            filterable?: boolean | null;
            /** Display Order */
            display_order?: number | null;
            /** Constraints */
            constraints?: {
                [key: string]: unknown;
            } | null;
            /** Expected Row Version */
            expected_row_version: number;
            /** Reason */
            reason: string;
        };
        /**
         * BindCodeRequest
         * @description The body of `POST /catalogue/entries/{business_key}/bindings`.
         *
         *     `code` is a string end-to-end (FR-06) - `nptc.catalogue.bindings.
         *     create_binding` validates it via `nptc_shared.sctid.SCTID` before any
         *     row is touched. `fsn`/`au_preferred_term` are carried through exactly
         *     as submitted (FR-82); this screen is the one place they are meant to be
         *     typed in, and neither is cleaned or re-derived here or anywhere else.
         */
        BindCodeRequest: {
            /** Code */
            code: string;
            /** Fsn */
            fsn: string;
            /** Au Preferred Term */
            au_preferred_term?: string | null;
            /** @default unknown */
            edition_hint: components["schemas"]["CodeBindingEditionHint"];
            /** Reason */
            reason: string;
        };
        /**
         * Binding
         * @description A SNOMED CT code binding, active or retired.
         *
         *     `code` is a string, always (FR-06). `display_term` is `fsn` with its
         *     semantic tag removed exactly once, by FR-83's single sanctioned
         *     renderer - it is derived here rather than stored, because a stored
         *     stripped value is indistinguishable from an unstripped one and that
         *     ambiguity is what makes double-stripping possible.
         *
         *     A retired binding carries `retirement_reason` and, where PRD FR-08's
         *     replacement case applies, `replaced_by_code` - the successor's *code*,
         *     which is what a client holding the retired one needs in order to move.
         */
        Binding: {
            /** System */
            system: string;
            /** Code */
            code: string;
            /** Fsn */
            fsn: string;
            /** Display Term */
            display_term: string;
            /** Au Preferred Term */
            au_preferred_term: string | null;
            /** Edition Hint */
            edition_hint: string;
            /** Status */
            status: string;
            /** Retirement Reason */
            retirement_reason: string | null;
            /** Replaced By Code */
            replaced_by_code: string | null;
        };
        /** BindingList */
        BindingList: {
            /** Items */
            items: components["schemas"]["Binding"][];
        };
        /**
         * BindingStrength
         * @enum {string}
         */
        BindingStrength: "required" | "extensible" | "example";
        /**
         * BindingTarget
         * @enum {string}
         */
        BindingTarget: "value_set" | "local_code_system";
        /**
         * CodeBindingEditionHint
         * @enum {string}
         */
        CodeBindingEditionHint: "au" | "int" | "unknown";
        /**
         * CollisionAcknowledgementResponse
         * @description Confirms an acknowledgement was recorded. No internal id, no
         *     `entry_id`, and deliberately no `acknowledged_by_user_id` either
         *     (NFR-04/NFR-26) - which administrator or reviewer acknowledged a
         *     collision is an audit-log fact, not a public response field.
         *
         *     `created` distinguishes "this call recorded it" (`True`) from "this
         *     exact `(entry, term, language)` was already acknowledged, by an earlier
         *     call" (`False`) - `acknowledge_collision` is idempotent (see its own
         *     docstring), and without this flag a caller cannot tell those two cases
         *     apart, nor notice that `reason` below is the *original* note rather
         *     than the one this call just submitted (issue #224 review finding 5).
         */
        CollisionAcknowledgementResponse: {
            /** Language */
            language: string;
            /** Reason */
            reason: string;
            /** Created */
            created: boolean;
        };
        /**
         * CollisionWarning
         * @description One warning-severity collision (FR-05): the same term active on
         *     another live entry. Names that entry's public identifier and preferred
         *     term, never its internal id (NFR-04/NFR-26) - the same shape the 409
         *     handler for the *error*-severity case already returns.
         */
        CollisionWarning: {
            /** Term */
            term: string;
            /** Business Key */
            business_key: string;
            /** Preferred Term */
            preferred_term: string;
        };
        /**
         * CreatePropertyDefinitionRequest
         * @description The body of `POST /registry/properties`. Every property created
         *     through this route is `origin = 'admin'` - there is no field to
         *     request otherwise; the four `origin = 'system'` rows are seeded once,
         *     at bootstrap, and never created through this API.
         *
         *     `cardinality`/`scope`/`strength`/`binding_target` are typed against the
         *     exact `StrEnum`s `property_definition`'s own database `CHECK`
         *     constraints close over (issue #223 review finding 3) - an invalid value
         *     is now a pydantic 422 before the request ever reaches the ORM, rather
         *     than a `23514` `IntegrityError` that `create_definition`'s `except
         *     IntegrityError` used to re-raise unchanged, surfacing as an unhandled
         *     500. `datatype` stays a bare `str` deliberately - FR-77's own extension
         *     point, so admitting a new datatype never touches this router - and is
         *     instead validated by `create_definition` itself, against the live
         *     `DatatypeRegistry`, where `UnknownDatatypeError` becomes a typed 422
         *     rather than a broken row that only misbehaves at the first value
         *     write.
         */
        CreatePropertyDefinitionRequest: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Datatype */
            datatype: string;
            cardinality: components["schemas"]["PropertyCardinality"];
            scope: components["schemas"]["PropertyScope"];
            /**
             * Required For Submission
             * @default false
             */
            required_for_submission: boolean;
            /**
             * Required For Publication
             * @default false
             */
            required_for_publication: boolean;
            /**
             * Filterable
             * @default false
             */
            filterable: boolean;
            /**
             * Display Order
             * @default 0
             */
            display_order: number;
            binding_target?: components["schemas"]["BindingTarget"] | null;
            /** Value Set Uri */
            value_set_uri?: string | null;
            strength?: components["schemas"]["BindingStrength"] | null;
            /** Edition */
            edition?: string | null;
            /** Local Code System Key */
            local_code_system_key?: string | null;
            /** Constraints */
            constraints?: {
                [key: string]: unknown;
            };
            /** Reason */
            reason: string;
        };
        /** DeprecatePropertyDefinitionRequest */
        DeprecatePropertyDefinitionRequest: {
            /** Expected Row Version */
            expected_row_version: number;
            /** Reason */
            reason: string;
        };
        /**
         * Designation
         * @description A catalogue-authored synonym, or a preferred variant in a language
         *     other than en-AU.
         *
         *     The catalogue's own en-AU preferred term is **not** here - it is
         *     `EntrySummary.preferred_term`, and ADR-0022 makes its absence from
         *     `designation` a database invariant rather than a convention. A client
         *     building a term list needs both: `preferred_term`, plus these.
         *
         *     No `id` (matching `Binding`'s own rule, NFR-04/NFR-26): issue #224's
         *     write router addresses a designation by term in the request body, not
         *     an internal identifier - see that router's own module docstring.
         */
        Designation: {
            /** Term */
            term: string;
            /** Use */
            use: string;
            /** Language */
            language: string;
            /** Status */
            status: string;
            /** Length */
            length: number;
        };
        /** DesignationList */
        DesignationList: {
            /** Items */
            items: components["schemas"]["Designation"][];
        };
        /**
         * DesignationUse
         * @enum {string}
         */
        DesignationUse: "preferred" | "synonym";
        /** DesignationWriteResult */
        DesignationWriteResult: {
            /** Designations */
            designations: components["schemas"]["Designation"][];
            /** Warnings */
            warnings: components["schemas"]["CollisionWarning"][];
        };
        /**
         * EntryDetail
         * @description A summary plus everything attached to the entry.
         *
         *     One response rather than making a client fetch four: the sub-resources
         *     are also served individually (a client refreshing one panel should not
         *     re-fetch the lot), but the common case is "show me this entry", and
         *     four round trips for one screen is a contract that pushes latency onto
         *     every consumer.
         */
        EntryDetail: {
            /** Business Key */
            business_key: string;
            /** Preferred Term */
            preferred_term: string;
            /** Length */
            length: number;
            /** Status */
            status: string;
            /** Specimen Unconstrained */
            specimen_unconstrained: boolean;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Designations */
            designations: components["schemas"]["Designation"][];
            /** Bindings */
            bindings: components["schemas"]["Binding"][];
            /** Properties */
            properties: components["schemas"]["PropertyValue"][];
        };
        /**
         * EntryPage
         * @description `next_cursor` is `null` on the last page - which is the *only*
         *     reliable signal that paging is finished. A client must not infer the end
         *     from a short page: a page can be short and still have a successor.
         */
        EntryPage: {
            /** Items */
            items: components["schemas"]["EntrySummary"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /**
         * EntrySummary
         * @description An entry as it appears in a list or a search result.
         *
         *     `length` is FR-85's published figure - the character count of the
         *     catalogue's own preferred term, computed by `CatalogueEntry.length` and
         *     never stored, so it cannot drift from the term it describes.
         */
        EntrySummary: {
            /** Business Key */
            business_key: string;
            /** Preferred Term */
            preferred_term: string;
            /** Length */
            length: number;
            /** Status */
            status: string;
            /** Specimen Unconstrained */
            specimen_unconstrained: boolean;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ErrorResponse
         * @description Every refusal this API makes has this shape - one sentence saying
         *     what to do next, and deliberately nothing else. It never names a role,
         *     a permission or an internal identifier (FR-44, NFR-04).
         */
        ErrorResponse: {
            /** Detail */
            detail: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * PropertyCardinality
         * @enum {string}
         */
        PropertyCardinality: "0..1" | "1..1" | "0..*" | "1..*";
        /** PropertyDefinitionList */
        PropertyDefinitionList: {
            /** Items */
            items: components["schemas"]["PropertyDefinitionResponse"][];
        };
        /**
         * PropertyDefinitionResponse
         * @description One `property_definition` row, on the wire. No internal id (NFR-04) -
         *     `key` is the one public identifier this resource is ever addressed by.
         */
        PropertyDefinitionResponse: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Datatype */
            datatype: string;
            /** Cardinality */
            cardinality: string;
            /** Scope */
            scope: string;
            /** Required For Submission */
            required_for_submission: boolean;
            /** Required For Publication */
            required_for_publication: boolean;
            /** Binding Target */
            binding_target: string | null;
            /** Value Set Uri */
            value_set_uri: string | null;
            /** Strength */
            strength: string | null;
            /** Edition */
            edition: string | null;
            /** Local Code System Key */
            local_code_system_key: string | null;
            /** Filterable */
            filterable: boolean;
            /** Origin */
            origin: string;
            /** Status */
            status: string;
            /** Display Order */
            display_order: number;
            /** Constraints */
            constraints: {
                [key: string]: unknown;
            };
            /** Row Version */
            row_version: number;
        };
        /** PropertyList */
        PropertyList: {
            /** Items */
            items: components["schemas"]["PropertyValue"][];
        };
        /**
         * PropertyScope
         * @enum {string}
         */
        PropertyScope: "submission" | "maintenance" | "both";
        /**
         * PropertyValue
         * @description One property value, rendered by its datatype's own handler.
         *
         *     `value` is whatever that handler's `serialise(..., JSON)` returns, so a
         *     new datatype (FR-77) appears here correctly without this module
         *     changing. `ordinal` is meaningful for a multi-valued property: it is the
         *     position of this value among that property's values, zero-based.
         */
        PropertyValue: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Datatype */
            datatype: string;
            /** Cardinality */
            cardinality: string;
            /** Ordinal */
            ordinal: number;
            /** Value */
            value: unknown;
            /** Justification */
            justification: string | null;
        };
        /**
         * ReplaceBindingRequest
         * @description One `reason` covers all three steps of the replacement (retire,
         *     create, link) - a caller explaining *why* a code is being replaced is
         *     explaining one editorial decision, not three.
         */
        ReplaceBindingRequest: {
            successor: components["schemas"]["ReplacementSuccessor"];
            /** Reason */
            reason: string;
        };
        /** ReplacementSuccessor */
        ReplacementSuccessor: {
            /** Code */
            code: string;
            /** Fsn */
            fsn: string;
            /** Au Preferred Term */
            au_preferred_term?: string | null;
            /** @default unknown */
            edition_hint: components["schemas"]["CodeBindingEditionHint"];
        };
        /** RetireBindingRequest */
        RetireBindingRequest: {
            /** Reason */
            reason: string;
        };
        /** RetireDesignationRequest */
        RetireDesignationRequest: {
            /**
             * Language
             * @default en-AU
             */
            language: string;
            /** Term */
            term: string;
            /** Reason */
            reason: string;
        };
        /**
         * SearchHit
         * @description A summary plus its relevance score.
         *
         *     The score is exposed because it is what the ordering is, and a client
         *     that cannot see it cannot tell a confident single match from a page of
         *     weak ones. It is comparable *within* one response only - it is a
         *     trigram similarity against this particular query, not a quality rating
         *     of the entry.
         */
        SearchHit: {
            /** Business Key */
            business_key: string;
            /** Preferred Term */
            preferred_term: string;
            /** Length */
            length: number;
            /** Status */
            status: string;
            /** Specimen Unconstrained */
            specimen_unconstrained: boolean;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Score
             * @description Trigram similarity against `q`, between 0 and 1.
             */
            score: number;
        };
        /** SearchPage */
        SearchPage: {
            /** Items */
            items: components["schemas"]["SearchHit"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /**
         * SessionResponse
         * @description What the browser is allowed to know about its own session.
         *
         *     `user` is `nptc.auth.identity.UserRef`, reused rather than redefined:
         *     it is this codebase's existing NFR-04 serialisation boundary and
         *     structurally excludes `app_user.id`. Defining a second response model
         *     with the same fields is exactly how that internal id eventually leaks.
         *
         *     `permissions` is present because the shell needs to decide what to
         *     *render*, and rendering is presentation, not access control (NFR-20) -
         *     every one of these permissions is re-checked server-side at the
         *     endpoint that uses it. `roles` is included for the account screen
         *     (FR-40), which shows a user their own roles.
         */
        SessionResponse: {
            /** Authenticated */
            authenticated: boolean;
            user: components["schemas"]["UserRef"] | null;
            /** Roles */
            roles: string[];
            /** Permissions */
            permissions: string[];
            /** Mfa Satisfied */
            mfa_satisfied: boolean;
        };
        /**
         * UserRef
         * @description The NFR-04 serialisation boundary: what any API response or export
         *     is allowed to say about a user. No ``id`` field, ever - the internal
         *     UUID must never escape past this type. #43/#142/#143 route through
         *     this structurally instead of relying on reviewer memory that the UUID
         *     must not leak.
         */
        UserRef: {
            /** Username */
            username: string | null;
            /** Display Name */
            display_name: string | null;
            /** Organisation */
            organisation: string | null;
            /** Status */
            status: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    read_current_session_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description No credential was presented where one is required, or the token could not be verified. Carries `WWW-Authenticate: Bearer`. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authenticated, but not permitted. When the permission would have been granted by a role suppressed for want of MFA, this carries an RFC 9470 `WWW-Authenticate: Bearer error="insufficient_user_authentication"` challenge instead of a bare denial (NFR-06). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The token resolved to more than one candidate account, or to an untrusted auto-link candidate. A human must resolve it (NFR-05). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_entries_api_v1_catalogue_entries_get: {
        parameters: {
            query?: {
                /** @description Maximum entries in this page. */
                limit?: number;
                /** @description The `next_cursor` from the previous page. Pass it back unmodified, and do not construct one. */
                after?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntryPage"];
                };
            };
            /** @description A credential was presented and could not be verified. Sending no credential at all is not an error on these endpoints. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A query or path parameter was unprocessable - a business key that is not `NPTC-nnnnnn`, a blank search query, a cursor this API did not issue (including one issued for a different `q`), or a `limit` outside its range. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    search_api_v1_catalogue_search_get: {
        parameters: {
            query: {
                /** @description Free text. Matched against each entry's preferred term and its active synonyms, insensitive to case and to diacritics, and tolerant of typographical error (FR-15). */
                q: string;
                /** @description Maximum entries in this page. */
                limit?: number;
                /** @description The `next_cursor` from the previous page. Opaque: pass it back unmodified, and do not construct one. It is bound to the `q` it was issued for - sending it with a different `q` is a 422, not a meaningless page. */
                after?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchPage"];
                };
            };
            /** @description A credential was presented and could not be verified. Sending no credential at all is not an error on these endpoints. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A query or path parameter was unprocessable - a business key that is not `NPTC-nnnnnn`, a blank search query, a cursor this API did not issue (including one issued for a different `q`), or a `limit` outside its range. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    read_entry_api_v1_catalogue_entries__business_key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The entry's public identifier, e.g. `NPTC-000247` (FR-03). */
                business_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntryDetail"];
                };
            };
            /** @description A credential was presented and could not be verified. Sending no credential at all is not an error on these endpoints. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No entry in the published catalogue has this business key. An entry that exists but is not published (draft, deprecated or withdrawn) is reported identically, on purpose - a distinguishable response would confirm the key exists. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A query or path parameter was unprocessable - a business key that is not `NPTC-nnnnnn`, a blank search query, a cursor this API did not issue (including one issued for a different `q`), or a `limit` outside its range. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A published code binding's stored Fully Specified Name is not in the form the terminology server serves, so its display term cannot be rendered. This is a data fault in the catalogue, not a fault in the request; it needs an administrator, and retrying will not clear it. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    read_designations_api_v1_catalogue_entries__business_key__designations_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The entry's public identifier, e.g. `NPTC-000247` (FR-03). */
                business_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DesignationList"];
                };
            };
            /** @description A credential was presented and could not be verified. Sending no credential at all is not an error on these endpoints. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No entry in the published catalogue has this business key. An entry that exists but is not published (draft, deprecated or withdrawn) is reported identically, on purpose - a distinguishable response would confirm the key exists. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A query or path parameter was unprocessable - a business key that is not `NPTC-nnnnnn`, a blank search query, a cursor this API did not issue (including one issued for a different `q`), or a `limit` outside its range. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    add_designations_api_v1_catalogue_entries__business_key__designations_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The entry's public identifier, e.g. `NPTC-000247` (FR-03). */
                business_key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddDesignationsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DesignationWriteResult"];
                };
            };
            /** @description No credential, or one that could not be verified. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The caller is authenticated but does not hold `catalogue.edit_published`, or holds it but has not completed the MFA step-up this permission requires (the response then also carries a `WWW-Authenticate` step-up challenge). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No catalogue entry, or no active designation, matches the given identifier. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request is well-formed but conflicts with the current state of the system - an error-severity collision against another entry (FR-05), a duplicate active term or a second active preferred term in one language on this same entry, a designation already retired, or a concurrent acknowledgement of the same collision. A term already retired, or never added, is a 404 here rather than a 409: every route below addresses a designation by its currently-*active* term, so a retired one is simply not addressable this way any more, not a conflicting state. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A field failed validation - an unrecognised `use`, a malformed language tag, a term that is empty after whitespace cleaning, or a changelog note that does not meet FR-37. Two distinct body shapes occur here: a typed domain error (`ErrorResponse`) or a pydantic validation failure (FastAPI's own `HTTPValidationError`). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"] | components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_bindings_api_v1_catalogue_entries__business_key__bindings_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The entry's public identifier, e.g. `NPTC-000247` (FR-03). */
                business_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BindingList"];
                };
            };
            /** @description A credential was presented and could not be verified. Sending no credential at all is not an error on these endpoints. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No entry in the published catalogue has this business key. An entry that exists but is not published (draft, deprecated or withdrawn) is reported identically, on purpose - a distinguishable response would confirm the key exists. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A query or path parameter was unprocessable - a business key that is not `NPTC-nnnnnn`, a blank search query, a cursor this API did not issue (including one issued for a different `q`), or a `limit` outside its range. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A published code binding's stored Fully Specified Name is not in the form the terminology server serves, so its display term cannot be rendered. This is a data fault in the catalogue, not a fault in the request; it needs an administrator, and retrying will not clear it. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    bind_code_api_v1_catalogue_entries__business_key__bindings_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The entry's public identifier, e.g. `NPTC-000247` (FR-03). */
                business_key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BindCodeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    /** @description The entry (`GET {business_key}`) the new binding was added to. */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Binding"];
                };
            };
            /** @description No credential, or one that could not be verified. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The caller is authenticated but does not hold `catalogue.edit_published`, or holds it but has not completed the MFA step-up this permission requires (the response then also carries a `WWW-Authenticate` step-up challenge). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No catalogue entry, or no active code binding, matches the given identifier. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request is well-formed but conflicts with the current state of the system - a second active binding on this entry, a successor code already actively bound elsewhere (including two concurrent requests racing for the same entry or code), or `/replacement`'s successor naming the same code it is meant to replace. A code already retired, or with no binding at all, is a 404 here rather than a 409: every route below addresses a binding by its currently-*active* code, so a retired one is simply not addressable this way any more, not a conflicting state. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A field failed validation - a malformed or Verhoeff-failing SCTID, an unrecognised edition hint, a blank `fsn`/`au_preferred_term`, or a changelog note that does not meet FR-37. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A platform-side invariant failed, not a caller mistake - e.g. re-reading a binding this same request just wrote could not find it. Not produced by anything a well-formed request can trigger on its own; retrying will not clear it. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    read_properties_api_v1_catalogue_entries__business_key__properties_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The entry's public identifier, e.g. `NPTC-000247` (FR-03). */
                business_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyList"];
                };
            };
            /** @description A credential was presented and could not be verified. Sending no credential at all is not an error on these endpoints. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No entry in the published catalogue has this business key. An entry that exists but is not published (draft, deprecated or withdrawn) is reported identically, on purpose - a distinguishable response would confirm the key exists. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A query or path parameter was unprocessable - a business key that is not `NPTC-nnnnnn`, a blank search query, a cursor this API did not issue (including one issued for a different `q`), or a `limit` outside its range. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    retire_binding_api_v1_catalogue_entries__business_key__bindings__code__retirement_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The entry's public identifier, e.g. `NPTC-000247` (FR-03). */
                business_key: string;
                code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetireBindingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Binding"];
                };
            };
            /** @description No credential, or one that could not be verified. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The caller is authenticated but does not hold `catalogue.edit_published`, or holds it but has not completed the MFA step-up this permission requires (the response then also carries a `WWW-Authenticate` step-up challenge). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No catalogue entry, or no active code binding, matches the given identifier. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request is well-formed but conflicts with the current state of the system - a second active binding on this entry, a successor code already actively bound elsewhere (including two concurrent requests racing for the same entry or code), or `/replacement`'s successor naming the same code it is meant to replace. A code already retired, or with no binding at all, is a 404 here rather than a 409: every route below addresses a binding by its currently-*active* code, so a retired one is simply not addressable this way any more, not a conflicting state. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A field failed validation - a malformed or Verhoeff-failing SCTID, an unrecognised edition hint, a blank `fsn`/`au_preferred_term`, or a changelog note that does not meet FR-37. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A platform-side invariant failed, not a caller mistake - e.g. re-reading a binding this same request just wrote could not find it. Not produced by anything a well-formed request can trigger on its own; retrying will not clear it. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    replace_binding_api_v1_catalogue_entries__business_key__bindings__code__replacement_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The entry's public identifier, e.g. `NPTC-000247` (FR-03). */
                business_key: string;
                code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplaceBindingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BindingList"];
                };
            };
            /** @description No credential, or one that could not be verified. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The caller is authenticated but does not hold `catalogue.edit_published`, or holds it but has not completed the MFA step-up this permission requires (the response then also carries a `WWW-Authenticate` step-up challenge). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No catalogue entry, or no active code binding, matches the given identifier. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request is well-formed but conflicts with the current state of the system - a second active binding on this entry, a successor code already actively bound elsewhere (including two concurrent requests racing for the same entry or code), or `/replacement`'s successor naming the same code it is meant to replace. A code already retired, or with no binding at all, is a 404 here rather than a 409: every route below addresses a binding by its currently-*active* code, so a retired one is simply not addressable this way any more, not a conflicting state. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A field failed validation - a malformed or Verhoeff-failing SCTID, an unrecognised edition hint, a blank `fsn`/`au_preferred_term`, or a changelog note that does not meet FR-37. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A platform-side invariant failed, not a caller mistake - e.g. re-reading a binding this same request just wrote could not find it. Not produced by anything a well-formed request can trigger on its own; retrying will not clear it. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    amend_designation_route_api_v1_catalogue_entries__business_key__designations_amendment_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The entry's public identifier, e.g. `NPTC-000247` (FR-03). */
                business_key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AmendDesignationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AmendDesignationResult"];
                };
            };
            /** @description No credential, or one that could not be verified. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The caller is authenticated but does not hold `catalogue.edit_published`, or holds it but has not completed the MFA step-up this permission requires (the response then also carries a `WWW-Authenticate` step-up challenge). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No catalogue entry, or no active designation, matches the given identifier. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request is well-formed but conflicts with the current state of the system - an error-severity collision against another entry (FR-05), a duplicate active term or a second active preferred term in one language on this same entry, a designation already retired, or a concurrent acknowledgement of the same collision. A term already retired, or never added, is a 404 here rather than a 409: every route below addresses a designation by its currently-*active* term, so a retired one is simply not addressable this way any more, not a conflicting state. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A field failed validation - an unrecognised `use`, a malformed language tag, a term that is empty after whitespace cleaning, or a changelog note that does not meet FR-37. Two distinct body shapes occur here: a typed domain error (`ErrorResponse`) or a pydantic validation failure (FastAPI's own `HTTPValidationError`). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"] | components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retire_designation_route_api_v1_catalogue_entries__business_key__designations_retirement_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The entry's public identifier, e.g. `NPTC-000247` (FR-03). */
                business_key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetireDesignationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Designation"];
                };
            };
            /** @description No credential, or one that could not be verified. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The caller is authenticated but does not hold `catalogue.edit_published`, or holds it but has not completed the MFA step-up this permission requires (the response then also carries a `WWW-Authenticate` step-up challenge). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No catalogue entry, or no active designation, matches the given identifier. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request is well-formed but conflicts with the current state of the system - an error-severity collision against another entry (FR-05), a duplicate active term or a second active preferred term in one language on this same entry, a designation already retired, or a concurrent acknowledgement of the same collision. A term already retired, or never added, is a 404 here rather than a 409: every route below addresses a designation by its currently-*active* term, so a retired one is simply not addressable this way any more, not a conflicting state. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A field failed validation - an unrecognised `use`, a malformed language tag, a term that is empty after whitespace cleaning, or a changelog note that does not meet FR-37. Two distinct body shapes occur here: a typed domain error (`ErrorResponse`) or a pydantic validation failure (FastAPI's own `HTTPValidationError`). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"] | components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    acknowledge_designation_collision_api_v1_catalogue_entries__business_key__designations_acknowledgement_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The entry's public identifier, e.g. `NPTC-000247` (FR-03). */
                business_key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcknowledgeCollisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollisionAcknowledgementResponse"];
                };
            };
            /** @description No credential, or one that could not be verified. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The caller is authenticated but does not hold `validation.acknowledge`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No catalogue entry, or no active designation, matches the given identifier. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request is well-formed but conflicts with the current state of the system - an error-severity collision against another entry (FR-05), a duplicate active term or a second active preferred term in one language on this same entry, a designation already retired, or a concurrent acknowledgement of the same collision. A term already retired, or never added, is a 404 here rather than a 409: every route below addresses a designation by its currently-*active* term, so a retired one is simply not addressable this way any more, not a conflicting state. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A field failed validation - an unrecognised `use`, a malformed language tag, a term that is empty after whitespace cleaning, or a changelog note that does not meet FR-37. Two distinct body shapes occur here: a typed domain error (`ErrorResponse`) or a pydantic validation failure (FastAPI's own `HTTPValidationError`). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"] | components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_properties_api_v1_registry_properties_get: {
        parameters: {
            query?: {
                include_deprecated?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyDefinitionList"];
                };
            };
            /** @description No credential, or one that could not be verified. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The caller is authenticated but does not hold `registry.read`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_property_api_v1_registry_properties_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePropertyDefinitionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyDefinitionResponse"];
                };
            };
            /** @description No credential, or one that could not be verified. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The caller is authenticated but does not hold `registry.manage`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request conflicts with the current state of the system - a duplicate `key`, an attempt to change `key`, a stale `expected_row_version`, a second deprecation, deprecating a system property, or (on `DELETE`) any request at all. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A field failed validation, the request body named a `key` field, or an explicit `null` was given for a field that is otherwise omittable. Two distinct body shapes occur here: a typed domain error (`ErrorResponse`) or a pydantic validation failure (FastAPI's own `HTTPValidationError`). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"] | components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_property_api_v1_registry_properties__key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyDefinitionResponse"];
                };
            };
            /** @description No credential, or one that could not be verified. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The caller is authenticated but does not hold `registry.read`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No property definition matches the given key. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_property_api_v1_registry_properties__key__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No credential, or one that could not be verified. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The caller is authenticated but does not hold `registry.manage`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request conflicts with the current state of the system - a duplicate `key`, an attempt to change `key`, a stale `expected_row_version`, a second deprecation, deprecating a system property, or (on `DELETE`) any request at all. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    amend_property_api_v1_registry_properties__key__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AmendPropertyDefinitionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyDefinitionResponse"];
                };
            };
            /** @description No credential, or one that could not be verified. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The caller is authenticated but does not hold `registry.manage`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No property definition matches the given key. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request conflicts with the current state of the system - a duplicate `key`, an attempt to change `key`, a stale `expected_row_version`, a second deprecation, deprecating a system property, or (on `DELETE`) any request at all. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A field failed validation, the request body named a `key` field, or an explicit `null` was given for a field that is otherwise omittable. Two distinct body shapes occur here: a typed domain error (`ErrorResponse`) or a pydantic validation failure (FastAPI's own `HTTPValidationError`). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"] | components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deprecate_property_api_v1_registry_properties__key__deprecation_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeprecatePropertyDefinitionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyDefinitionResponse"];
                };
            };
            /** @description No credential, or one that could not be verified. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The caller is authenticated but does not hold `registry.manage`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No property definition matches the given key. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request conflicts with the current state of the system - a duplicate `key`, an attempt to change `key`, a stale `expected_row_version`, a second deprecation, deprecating a system property, or (on `DELETE`) any request at all. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A field failed validation, the request body named a `key` field, or an explicit `null` was given for a field that is otherwise omittable. Two distinct body shapes occur here: a typed domain error (`ErrorResponse`) or a pydantic validation failure (FastAPI's own `HTTPValidationError`). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"] | components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
