"""FR-72 acceptance criterion 1 - proves the grouped report by *round-tripping*
``report.md`` against ``report.json``, not by scanning for substrings.

A substring check (``"WHITESPACE_ONLY_CELL" in text``) cannot catch a
grouping bug that puts a finding under the wrong heading, or a message whose
own ``|`` silently splits its table row into a *different* number of columns
while every substring it contains still, individually, appears somewhere on
the page. Walking the rendered Markdown back into the same
``(band, code, ref, message)`` shape ``report.json`` already carries, and
comparing the two as sets, is what actually proves the human-readable
artefact says what the machine-readable one says.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import openpyxl
import pytest
from openpyxl.utils import column_index_from_string

from nptc_transform.actions import action_for
from nptc_transform.bands import FindingCode
from nptc_transform.cellref import CellRef
from nptc_transform.findings import Finding
from nptc_transform.pipeline import Mode, RunResult, SourceRef, run_transform
from nptc_transform.report_writer import write_report

_BAND_HEADING_RE = re.compile(r"^### (?P<band>.+?)(?: - blocks import)?$")
_CODE_HEADING_RE = re.compile(r"^#### `(?P<code>.+)` - \d+ finding\(s\)$")
_ACTION_RE = re.compile(r"^\*\*Required action:\*\* (?P<action>.+)$")

#: The Cell column is a CommonMark code span whose fence is a backtick run
#: longer than any run inside the value (``report_writer._code_span``), with
#: an optional single space of padding - not always a single backtick - so
#: the fence itself has to be captured and referred back to, not assumed.
_ROW_RE = re.compile(r"^\| (?P<fence>`+) ?(?P<cell>.*?) ?(?P=fence) \| (?P<detail>.*) \|$")

Finding_ = tuple[str, str, str, str]  # (band, code, ref, message)


def _unescape_cell(value: str) -> str:
    """Inverts ``report_writer._escape_cell`` for the specific escape shapes
    this test's own fixture data produces - not a general codec, since the
    fixture never nests a literal backslash next to a literal pipe. Does not
    unescape a backtick: the Cell column no longer escapes one (it uses a
    variable-length fence instead - see ``_ROW_RE``), and the Detail column
    never did (a message's backtick is legal, unescaped Markdown)."""
    return value.replace("<br>", "\n").replace("\\|", "|").replace("\\\\", "\\")


def _findings_in_markdown(text: str) -> set[Finding_]:
    band: str | None = None
    code: str | None = None
    out: set[Finding_] = set()
    for line in text.splitlines():
        band_match = _BAND_HEADING_RE.match(line)
        code_match = _CODE_HEADING_RE.match(line)
        row_match = _ROW_RE.match(line)
        if band_match:
            band, code = band_match.group("band"), None
            continue
        if code_match:
            code = code_match.group("code")
            continue
        if row_match and band is not None and code is not None:
            ref = _unescape_cell(row_match.group("cell"))
            detail = _unescape_cell(row_match.group("detail"))
            out.add((band, code, ref, detail))
    return out


def _actions_in_markdown(text: str) -> dict[str, str]:
    """Maps each rendered ``#### \\`CODE\\``` heading to the required-action
    paragraph immediately below it (Test 3's own shape)."""
    code: str | None = None
    out: dict[str, str] = {}
    for line in text.splitlines():
        code_match = _CODE_HEADING_RE.match(line)
        action_match = _ACTION_RE.match(line)
        if code_match:
            code = code_match.group("code")
            continue
        if action_match and code is not None:
            out[code] = action_match.group("action")
            code = None
    return out


def _findings_in_json(payload: dict[str, object]) -> set[Finding_]:
    out: set[Finding_] = set()
    for defect_class in payload["defect_classes"]:  # type: ignore[union-attr]
        band = defect_class["band"]
        code = defect_class["code"]
        for finding in defect_class["findings"]:
            out.add((band, code, finding["location"]["ref"], finding["message"]))
    return out


def _build_result() -> RunResult:
    """One ``Finding`` per ``FindingCode`` member (generated by iterating the
    enum, so a future code cannot be forgotten), plus the specific edge cases
    AC-1's round trip must survive."""
    findings = [
        Finding(
            code=code,
            location=CellRef("Sheet1", "B", index + 2),
            message=f"message for {code}",
        )
        for index, code in enumerate(FindingCode)
    ]
    findings.append(
        Finding(code="UNREGISTERED_FUTURE_CODE", location=CellRef("Sheet1", "C", 2), message="x")
    )
    findings.append(
        Finding(
            code=FindingCode.WHITESPACE_ONLY_CELL,
            location=CellRef("Sheet1", "D", 2),
            message="a second finding sharing a code",
        )
    )
    findings.append(
        Finding(
            code=FindingCode.SURROUNDING_WHITESPACE,
            location=CellRef("Sales!Q1", "B", 5),  # a sheet name containing '!'
            message="clean, unambiguous message",
        )
    )
    findings.append(
        Finding(
            code=FindingCode.CODE_NOT_WELL_FORMED,
            location=CellRef("Sheet1", "E", 2),
            message="value was 'a|b' and had a break\nsecond line",
        )
    )
    findings.append(
        Finding(
            code=FindingCode.CODE_NOT_FOUND, location=CellRef("Sheet1", "F", 2), message="row two"
        )
    )
    findings.append(
        Finding(
            code=FindingCode.CODE_NOT_FOUND, location=CellRef("Sheet1", "F", 10), message="row ten"
        )
    )
    findings.append(
        Finding(
            code=FindingCode.CODE_INACTIVE,
            location=CellRef("Q1`draft", "G", 2),  # a sheet name containing '`'
            message="clean message",
        )
    )
    return RunResult(
        source=SourceRef(filename="sample.xlsx", sha256="a" * 64),
        mode=Mode.REPORT_ONLY,
        findings=tuple(findings),
    )


@pytest.mark.req("FR-72")
def test_every_finding_round_trips_between_markdown_and_json(tmp_path: Path) -> None:
    result = _build_result()
    report_dir = tmp_path / "report"

    write_report(result, report_dir)

    markdown_text = (report_dir / "report.md").read_text(encoding="utf-8")
    payload = json.loads((report_dir / "report.json").read_text(encoding="utf-8"))

    md_findings = _findings_in_markdown(markdown_text)
    json_findings = _findings_in_json(payload)

    assert md_findings == json_findings
    assert len(json_findings) == payload["finding_count"] == len(result.findings)


@pytest.mark.req("FR-72")
def test_a_pipe_in_the_message_does_not_desynchronise_the_round_trip(tmp_path: Path) -> None:
    """Principal failure mode for AC-1: an unescaped ``|`` in a finding's
    message would split its table row into an extra column, so the finding
    reads as present-but-non-corresponding while every substring-based check
    still passes. Isolated here so a regression names the actual cause."""
    result = RunResult(
        source=SourceRef(filename="sample.xlsx", sha256="a" * 64),
        mode=Mode.REPORT_ONLY,
        findings=(
            Finding(
                code=FindingCode.CODE_NOT_WELL_FORMED,
                location=CellRef("Sheet1", "B", 2),
                message="value was 'a|b'",
            ),
        ),
    )
    report_dir = tmp_path / "report"

    write_report(result, report_dir)

    markdown_text = (report_dir / "report.md").read_text(encoding="utf-8")
    payload = json.loads((report_dir / "report.json").read_text(encoding="utf-8"))

    assert _findings_in_markdown(markdown_text) == _findings_in_json(payload)


@pytest.mark.req("FR-72")
def test_a_backtick_in_the_cell_reference_does_not_close_the_code_span_early(
    tmp_path: Path,
) -> None:
    """Principal failure mode for the cell column's code span: a sheet name
    may legally contain a backtick (Excel forbids only ``: \\ / ? * []``),
    and backslash escapes are inert inside a code span (CommonMark), so
    escaping it would not stop it from closing the span mid-reference -
    ``_code_span`` uses a longer backtick fence instead. This is the same
    desynchronisation shape an unescaped ``|`` has, but in the delimiter
    added specifically for this rendering, not the escaping this module
    already had for the row itself."""
    result = RunResult(
        source=SourceRef(filename="sample.xlsx", sha256="a" * 64),
        mode=Mode.REPORT_ONLY,
        findings=(
            Finding(
                code=FindingCode.CODE_INACTIVE,
                location=CellRef("Q1`draft", "B", 2),
                message="clean message",
            ),
        ),
    )
    report_dir = tmp_path / "report"

    write_report(result, report_dir)

    markdown_text = (report_dir / "report.md").read_text(encoding="utf-8")
    payload = json.loads((report_dir / "report.json").read_text(encoding="utf-8"))

    assert _findings_in_markdown(markdown_text) == _findings_in_json(payload)


@pytest.mark.req("FR-72")
def test_every_rendered_heading_carries_its_registered_required_action(tmp_path: Path) -> None:
    result = _build_result()
    report_dir = tmp_path / "report"

    write_report(result, report_dir)

    markdown_text = (report_dir / "report.md").read_text(encoding="utf-8")
    rendered_actions = _actions_in_markdown(markdown_text)

    assert rendered_actions  # the fixture must produce at least one heading
    for code, action in rendered_actions.items():
        assert action == action_for(code)


# -- AC-2: "resolvable back to the source workbook" --------------------------


@pytest.mark.req("FR-72")
def test_a_cell_level_finding_resolves_to_the_actual_defective_cell(tmp_path: Path) -> None:
    """AC-1 (above) proves every finding *carries* a structured location.
    That is true by construction for a ``CellRef`` and would pass even with a
    0-based/1-based row error or a letter/index mix-up in ``workbook.py``.
    The test that actually earns AC-2's "resolvable" claim has to re-open the
    same workbook with openpyxl and read the exact cell a finding names.

    Excludes the two sheet-level findings (``UNRECOGNISED_LAYOUT``/
    ``SHEET_NOT_SPIA_DATA``), which point at the header cell ``A1``, not a
    defective cell - ``test_cell_defects.py::test_unrecognised_layout_flags_
    the_missing_code_column`` keeps owning that case.
    """
    nbsp = chr(0x00A0)
    path = tmp_path / "resolvable.xlsx"
    workbook = openpyxl.Workbook()
    sheet = workbook.active
    assert sheet is not None
    sheet.title = "Requesting"
    sheet.append(
        ["Terminology binding (SNOMED CT-AU)", "RCPA Synonyms", "Some Column", "Another Column"]
    )
    for row in range(2, 12):
        sheet.cell(row=row, column=1, value=f"{10000000 + row}")  # a clean, text code cell
        sheet.cell(row=row, column=2, value="clean")
        sheet.cell(row=row, column=3, value="clean")
        sheet.cell(row=row, column=4, value="clean")
    sheet.cell(row=9, column=2, value="   ")  # WHITESPACE_ONLY_CELL
    sheet.cell(row=7, column=4, value=f"clean{nbsp}")  # INVISIBLE_CHARACTER
    workbook.save(path)

    result = run_transform(path, mode=Mode.REPORT_ONLY)

    cell_level = [
        finding
        for finding in result.findings
        if finding.code not in (FindingCode.UNRECOGNISED_LAYOUT, FindingCode.SHEET_NOT_SPIA_DATA)
    ]
    assert cell_level, "fixture must produce at least one cell-level finding"

    reopened = openpyxl.load_workbook(path, read_only=True, data_only=False)
    try:
        for finding in cell_level:
            location = finding.location
            worksheet = reopened[location.sheet]
            value = worksheet.cell(
                row=location.row, column=column_index_from_string(location.column_letter)
            ).value
            assert isinstance(value, str)
            if finding.code == FindingCode.WHITESPACE_ONLY_CELL:
                assert not value.strip()
            elif finding.code == FindingCode.INVISIBLE_CHARACTER:
                assert nbsp in value
    finally:
        reopened.close()
